apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-services
  labels:
    app: pcc-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pcc-services
  template:
    metadata:
      labels:
        app: pcc-services
    spec:
      containers:
        - name: pcc-services
          image: diogojms/pcc_services:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://DriveCleaner:DriveCleanerG7@cluster0.bj3pzfe.mongodb.net/Services"
            - name: SECRET
              value: "jfcnbjsnwdelwjcnewdlejbsfew"
            - name: LOGS_URI
              value: "guest:guest@localhost:5672/"
