apiVersion: v1
kind: Service
metadata:
  name: pcc-services
  labels:
    app: pcc-services
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8084
  selector:
    app: pcc-services
  sessionAffinity: None
